appName: backend
appReplicas: 1
appImage: abanobmorkos10/backend_pwc:41
containerEnvVars:
- name: MONGO_CONN_STR
  value: mongodb://mongodb-svc:27017/todo?directConnection=true
- name: MONGO_USERNAME
  valueFrom:
    secretKeyRef:
      name: mongo-sec
      key: username
- name: MONGO_PASSWORD
  valueFrom:
    secretKeyRef:
      name: mongo-sec
      key: password
containerPort: 80
servicePort: 80
serviceType: LoadBalancer
serviceAnnotations:
  service.beta.kubernetes.io/aws-load-balancer-internal: "false"