appName: backend
appReplicas: 1
appImage: abanobmorkos10/backend_pwc:18
containerEnvVars:
- name: MONGO_CONN_STR
  value: mongodb://mongodb-svc:27017/todo?directConnection=true
- name: MONGO_USERNAME
  valueFrom:
    secretKeyRef:
      name: mongo-sec
      key: username
- name: MONGO_PASSWORD
  valueFrom:
    secretKeyRef:
      name: mongo-sec
      key: password
containerPort: 8080
servicePort: 8080
serviceType: LoadBalancer
serviceAnnotations:
  service.beta.kubernetes.io/aws-load-balancer-internal: "false"