apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    role: {{ .Values.appName }}
    env: demo
spec:
  replicas: {{ .Values.appReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: {{ .Values.appName }}
  template:
    metadata:
      labels:
        role: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.appImage }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.containerPort }}
        {{- if .Values.containerEnvVars }}
        env:
        {{- range .Values.containerEnvVars }}
        - name: {{ .name }}
          {{- if .valueFrom }}
          valueFrom:
            secretKeyRef:
              name: {{ .valueFrom.secretKeyRef.name }}
              key: {{ .valueFrom.secretKeyRef.key }}
          {{- else }}
          value: {{ .value }}
          {{- end }}
        {{- end }}
        {{- end }}
