apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  {{- if .Values.serviceAnnotations }}
  annotations:
  {{- range $key, $value := .Values.serviceAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
  type: {{ .Values.serviceType }}
  selector:
    role: {{ .Values.appName }}

